export enum SchoolYear {
  Inicial1 = "Inicial 1 (3 años)",
  Inicial2 = "Inicial 2 (4 años)",
  Inicial3 = "Inicial 3 (5 años)",
  Primaria1 = "1° Primaria",
  Primaria2 = "2° Primaria",
  Primaria3 = "3° Primaria",
  Primaria4 = "4° Primaria",
  Primaria5 = "5° Primaria",
  Primaria6 = "6° Primaria",
  Secundaria7 = "7° Secundaria (1° Ciclo Básico)",
  Secundaria8 = "8° Secundaria (2° Ciclo Básico)",
  Secundaria9 = "9° Secundaria (3° Ciclo Básico)",
  Bachillerato10 = "10° Secundaria (1° Bachillerato)",
  Bachillerato11 = "11° Secundaria (2° Bachillerato)",
  Bachillerato12 = "12° Secundaria (3° Bachillerato)",
}
